# Generated by Django 5.1.1 on 2024-12-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_alter_infraestructura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='estado',
            field=models.CharField(default='', max_length=64, verbose_name='Estado:'),
        ),
    ]
