# Generated by Django 5.1.1 on 2024-12-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-id'], 'permissions': [('listar_articulo', 'Puede listar articulos'), ('agregar_articulo', 'Puede agregar articulo'), ('ver_articulo', 'Puede ver articulo'), ('editar_articulo', 'Puede actualizar articulo'), ('eliminar_articulo', 'Puede eliminar articulo')], 'verbose_name': 'Actividad social', 'verbose_name_plural': 'Actividades sociales'},
        ),
        migrations.AlterModelOptions(
            name='tipoarticulo',
            options={'ordering': ['-id'], 'permissions': [('listar_type_articulo', 'Puede listar tipos de articulos'), ('agregar_type_articulo', 'Puede agregar tipo de articulo'), ('ver_type_articulo', 'Puede ver tipo de articulo'), ('editar_type_articulo', 'Puede actualizar tipo de articulo'), ('eliminar_type_articulo', 'Puede eliminar tipo de articulo')], 'verbose_name': 'Tipo de Articulo', 'verbose_name_plural': 'Tipos de Articulos'},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='user',
        ),
        migrations.AlterField(
            model_name='tipoarticulo',
            name='nombre',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterModelTable(
            name='articulo',
            table='administracion_articulos',
        ),
        migrations.AlterModelTable(
            name='tipoarticulo',
            table='administracion_tipos_articulos',
        ),
    ]
