# Generated by Django 5.1.1 on 2024-12-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_articulo_options_alter_tipoarticulo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['-id'], 'permissions': [('listar_asignacion', 'Puede listar asignacions'), ('agregar_asignacion', 'Puede agregar asignacion'), ('ver_asignacion', 'Puede ver asignacion'), ('editar_asignacion', 'Puede actualizar asignacion'), ('eliminar_asignacion', 'Puede eliminar asignacion')], 'verbose_name': 'Asignacion', 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='user',
        ),
        migrations.AlterModelTable(
            name='asignacion',
            table='administracion_asignacion',
        ),
    ]
