# Generated by Django 5.1.1 on 2024-12-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accion',
            options={'verbose_name': 'Accion', 'verbose_name_plural': 'Acciones'},
        ),
    ]
