# Generated by Django 5.1.1 on 2024-11-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('telefono', models.CharField(default='', max_length=64, verbose_name='Teléfono:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('direccion', models.CharField(default='', max_length=64, verbose_name='Dirección:')),
                ('cargo', models.CharField(default='', max_length=64, verbose_name='Cargo:')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora de Entrada:')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
            },
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('tipo', models.CharField(default='', max_length=64, verbose_name='Tipo de Incidente:')),
                ('descripcion', models.CharField(default='', max_length=64, verbose_name='Descripción:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('direccion', models.CharField(default='', max_length=64, verbose_name='Dirección:')),
                ('cargo', models.CharField(default='', max_length=64, verbose_name='Cargo:')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora de Entrada:')),
            ],
            options={
                'verbose_name': 'gestion',
                'verbose_name_plural': 'gestiones',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('telefono', models.CharField(default='', max_length=64, verbose_name='Teléfono:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('direccion', models.CharField(default='', max_length=64, verbose_name='Dirección:')),
                ('cargo', models.CharField(default='', max_length=64, verbose_name='Cargo:')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora de Entrada:')),
            ],
            options={
                'verbose_name': 'salida',
                'verbose_name_plural': 'salidas',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('nombre', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('modelo', models.CharField(default='', max_length=64, verbose_name='Modelo:')),
                ('vehiculo', models.CharField(default='', max_length=64, verbose_name='Tipo de vehiculo:')),
                ('motivo', models.CharField(default='', max_length=64, verbose_name='Motivo:')),
                ('capagasolina', models.CharField(default='', max_length=64, verbose_name='Capacidad de Gasolina:')),
                ('cantigasolina', models.CharField(default='', max_length=64, verbose_name='Capacidad de Gasolina:')),
                ('placa', models.CharField(default='', max_length=64, verbose_name='Placa:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora:')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
            },
        ),
    ]
