# Generated by Django 5.1.1 on 2024-11-24 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoCompetente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('denunciante', models.CharField(max_length=255)),
                ('telefono_denunciante', models.CharField(blank=True, max_length=255)),
                ('direccion_incidencia', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.estado')),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.municipio')),
                ('id_parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.parroquia')),
                ('id_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencia.incidencia')),
                ('id_organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencia.organismocompetente')),
            ],
            options={
                'verbose_name': 'emergencia',
                'verbose_name_plural': 'emergencias',
            },
        ),
    ]
